### ISSUE TITLE
Get better web dev support!

### ISSUE THREAD

**Issue by trevor-utilityapi** [trevorhauter/nvtrev#5]
The syntax highlighting and autocomplete for CSS/HTML sucks right now! And no django support!

Boooo! Let's fix it!

**Comment by trevorhauter** [comment]
Take a look at this!
https://blog.inkdrop.app/my-neovim-setup-for-react-typescript-tailwind-css-etc-in-2022-a7405862c9a4

**Comment by trevor-utilityapi** [comment]
Actually the web dev support is pretty good, and issue #12 should hopefully help us get the last pieces of the puzzle
